### ISSUE TITLE
Unique strings are not correctly processed

### ISSUE THREAD

**Issue by yoeljacobsen** [defunkydrummer/lisp-xl#1]
For some files unique strings are not correctly processed.

A Sample file is attached: [o1.xlsx](https://github.com/defunkydrummer/lisp-xl/files/1926982/o1.xlsx)

For row 4, instead of:
`("#" "SKU" "Description" "Q-ty" "Unit Selling Price" "Total Selling Price" "Config")`

`(process-sheet)` returns:
`("#" 3 4 "Q-ty" 6 7 "Config")`

**Comment by defunkydrummer** [comment]
@yoeljacobsen  Thanks for submitting this; i'll try to have a look as soon as possible. I have updated the code specifically at the part of the unique-strings as well, because i have had many problems with some files over 600000 rows in size. I'll take a look as soon as I have some free time.

**Comment by defunkydrummer** [comment]
@yoeljacobsen  I'm sorry to have taken so long.
I took a look of your excel file, and the cells named "SKU" and "Description" are formatted as *number* on your excel file, that's why they aren't loaded correctly. 

I'm sorry but I would consider that a 'malformed' excel.
