### ISSUE TITLE
Reading value produced by cell formula

### ISSUE THREAD

**Issue by hilmandayo** [defunkydrummer/lisp-xl#4]
Hey, thank you for the library.

I am trying to read data from an xlsx file, but I have a problem reading a cell in which there is a formula in it. It seems like the formula is read instead of the value produced by the formula. How can I solve this problem?

**Comment by defunkydrummer** [comment]
This can't be solved since it would require evaluating all formulas and thus implementing part of the excel calculation engine!!

The only way to solve it is to use excel to copy the entire sheet to a new sheet using the "Paste values..." option, so the values (and not the formulas) are copied.
